-- Add missing PolicyType enum values
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'AI_FAIR_USE_POLICY';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'GDPR_DATA_PROCESSING_ADDENDUM';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'COMPLAINTS_POLICY';
