name: Deploy to Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app (if needed)
        run: npm run build --if-present

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem bitnami@$LIGHTSAIL_IP << 'EOF'
            cd /home/bitnami/htdocs/compliance-back
            git pull origin main
            npm ci --production
            npx prisma migrate deploy || true
            pm2 reload all || pm2 start server.js --name "myapp"
            pm2 save
          EOF

          rm -f private_key.pem
