name: Deploy to Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app (if needed)
        run: npm run build --if-present

      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem bitnami@$LIGHTSAIL_IP << 'EOF'
            set -e  # Exit on any error

            cd /home/bitnami/htdocs/compliance-back

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies (including Prisma)..."
            npm ci

            echo "Running database migrations..."
            npx prisma migrate deploy

            echo "Generating Prisma Client..."
            npx prisma generate

            echo "Restarting application with PM2..."
            pm2 reload compliance-backend --update-env || pm2 start src/server.js --name "compliance-backend"
            pm2 save

            echo "Deployment completed successfully!"
          EOF

          rm -f private_key.pem
